In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
data=Series([1,2,3,4,5,6,7,8,9],index=['ID1','ID2','ID3','ID4','ID5','ID6','ID7','ID8','ID9'])
print('序列中的值:\n{0}'.format(data.values))
print('序列中的索引:\n{0}'.format(data.index))
print('访问序列的第1和第3上的值:\n{0}'.format(data[[0,2]]))
print('访问序列索引为ID1和ID3上的值:\n{0}'.format(data[['ID1','ID3']]))
print('判断ID1索引是否存在:%s；判断ID10索引是否存在:%s'%('ID1' in data,'ID10' in data))

序列中的值:
[1 2 3 4 5 6 7 8 9]
序列中的索引:
Index(['ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'ID6', 'ID7', 'ID8', 'ID9'], dtype='object')
访问序列的第1和第3上的值:
ID1    1
ID3    3
dtype: int64
访问序列索引为ID1和ID3上的值:
ID1    1
ID3    3
dtype: int64
判断ID1索引是否存在:True；判断ID10索引是否存在:False


代码说明：
（1）第2，3行：导入Pandas且指定别名为pd。导入pandas模块下的序列和数据框。
（2）第4行：利用Pandas的函数Series()生成一个包含9个元素（取值为1至9）的序列，且指定各元素的索引名依次为ID1,ID2等。后续可通过索引访问相应元素。
（3）第5行：序列的.values属性中存储着各元素的元素值。
（4）第6行：序列的.index属性中存储着各元素的索引。
（5）第7行：利用索引号（从0开始）访问指定元素。应以列表形式（如[0,2]）指定多个索引号。
（6）第8行：利用索引名访问指定元素。索引名应用单引号括起来。应以列表形式（如[‘ID1’,’ID3’]）指定多个索引名。
（7）第9行：利用Python运算符in，判断是否存在某个索引名。若存在判断结果为True（真），否则为False（假）。True和False是Python的布尔型变量的仅有的取值。


In [2]:
import pandas as pd
from pandas import Series,DataFrame
data=pd.read_excel('北京市空气质量数据.xlsx')
print('date的类型：{0}'.format(type(data)))
print('数据框的行索引：{0}'.format(data.index))
print('数据框的列名：{0}'.format(data.columns))
print('访问AQI和PM2.5所有值：\n{0}'.format(data[['AQI','PM2.5']]))
print('访问第2至3行的AQI和PM2.5：\n{0}'.format(data.loc[1:2,['AQI','PM2.5']]))
print('访问索引1至索引2的第2和4列：\n{0}'.format(data.iloc[1:3,[1,3]]))
data.info()

date的类型：<class 'pandas.core.frame.DataFrame'>
数据框的行索引：RangeIndex(start=0, stop=2155, step=1)
数据框的列名：Index(['日期', 'AQI', '质量等级', 'PM2.5', 'PM10', 'SO2', 'CO', 'NO2', 'O3'], dtype='object')
访问AQI和PM2.5所有值：
      AQI  PM2.5
0      81     45
1     145    111
2      74     47
3     149    114
4     119     91
...   ...    ...
2150  183    138
2151  175    132
2152   30      7
2153   40     13
2154   73     38

[2155 rows x 2 columns]
访问第2至3行的AQI和PM2.5：
   AQI  PM2.5
1  145    111
2   74     47
访问索引1至索引2的第2和4列：
   AQI  PM2.5
1  145    111
2   74     47
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 9 columns):
日期       2155 non-null datetime64[ns]
AQI      2155 non-null int64
质量等级     2155 non-null object
PM2.5    2155 non-null int64
PM10     2155 non-null int64
SO2      2155 non-null int64
CO       2155 non-null float64
NO2      2155 non-null int64
O3       2155 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(6), object(1)
memory us

代码说明：
（1）第3行：利用Pandas函数read_excel()将一个Excel文件（北京市空气质量数据.xlsx）读入到数据框中。
（2）第4行：利用Python函数type()浏览对象data的类型，结果显示为数据框。
（3）第5，6行：数据框的.index和.columns属性中存储着数据框的行索引和列索引名。这里，行索引默认取值：0至样本量N-1。列索引名默认为数据文件中第一行的变量名。
（4）第7行：利用列索引名访问指定变量。多个列索引名应以列表形式放在方括号中（[‘AQI’,’PM2.5’]）。
（5）第8行：利用数据框的.loc属性访问指定行索引和变量名上的元素。
注意：数据框对应二维表格，应给两个索引。
（6）第9行：利用数据框的.iloc属性访问指定行索引和列索引号上的元素。
注意：使用行索引时冒号:后的行不包括在内
（7）第10行：利用数据框的info()方法显示数据框的行索引、列索引以及数据类型等信息。


In [3]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
df1=DataFrame({'key':['a','d','c','a','b','d','c'],'var1':range(7)})
df2=DataFrame({'key':['a','b','c','c'],'var2':[0,1,2,2]})
df=pd.merge(df1,df2,on='key',how='outer')
df.iloc[0,2]=np.NaN
df.iloc[5,1]=np.NaN
print('合并后的数据:\n{0}'.format(df))
df=df.drop_duplicates()
print('删除重复数据行后的数据:\n{0}'.format(df))
print('判断是否为缺失值:\n{0}'.format(df.isnull()))
print('判断是否不为缺失值:\n{0}'.format(df.notnull()))
print('删除缺失值后的数据:\n{0}'.format(df.dropna()))
fill_value=df[['var1','var2']].apply(lambda x:x.mean())
print('以均值替换缺失值:\n{0}'.format(df.fillna(fill_value)))

合并后的数据:
  key  var1  var2
0   a   0.0   NaN
1   a   3.0   0.0
2   d   1.0   NaN
3   d   5.0   NaN
4   c   2.0   2.0
5   c   NaN   2.0
6   c   6.0   2.0
7   c   6.0   2.0
8   b   4.0   1.0
删除重复数据行后的数据:
  key  var1  var2
0   a   0.0   NaN
1   a   3.0   0.0
2   d   1.0   NaN
3   d   5.0   NaN
4   c   2.0   2.0
5   c   NaN   2.0
6   c   6.0   2.0
8   b   4.0   1.0
判断是否为缺失值:
     key   var1   var2
0  False  False   True
1  False  False  False
2  False  False   True
3  False  False   True
4  False  False  False
5  False   True  False
6  False  False  False
8  False  False  False
判断是否不为缺失值:
    key   var1   var2
0  True   True  False
1  True   True   True
2  True   True  False
3  True   True  False
4  True   True   True
5  True  False   True
6  True   True   True
8  True   True   True
删除缺失值后的数据:
  key  var1  var2
1   a   3.0   0.0
4   c   2.0   2.0
6   c   6.0   2.0
8   b   4.0   1.0
以均值替换缺失值:
  key  var1  var2
0   a   0.0   1.4
1   a   3.0   0.0
2   d   1.0   1.4
3   d   5.0   1.4
4   c   2.

代码说明：
（1）第4，5行：基于Python字典建立数据框。
（2）第6行：利用Pandas函数merge()将两个数据框依指定关键字做横向合并，生成一个新数据框。
（3）第7，8行：人为指定某样本观测的某变量值为NaN。
（4）第10行：利用Pandas函数drop_duplicates()剔除数据框中在全部变量上均重复取值的样本观测。
（5）第12，13行：利用数据框的.isnull()和.notnull()方法，对数据框中的每个元素判断其是否为NaN或不是NaN，结果为True或False。
（6）第14行：利用数据框.dropna()方法剔除取NaN的样本观测。
（7）第15行：利用数据框.apply()方法以及匿名函数计算各个变量的均值，并存储在名为fill_value的序列中。
（8）第16行：利用数据框的.fillna()方法，将所有NaN替换为指定值（这里为fill_value）。

In [4]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

data=pd.read_excel('北京市空气质量数据.xlsx')
data=data.replace(0,np.NaN)
data['年']=data['日期'].apply(lambda x:x.year)
month=data['日期'].apply(lambda x:x.month)
quarter_month={'1':'一季度','2':'一季度','3':'一季度',
               '4':'二季度','5':'二季度','6':'二季度',
               '7':'三季度','8':'三季度','9':'三季度',
              '10':'四季度','11':'四季度','12':'四季度'}
data['季度']=month.map(lambda x:quarter_month[str(x)])
bins=[0,50,100,150,200,300,1000]
data['等级']=pd.cut(data['AQI'],bins,labels=['一级优','二级良','三级轻度污染','四级中度污染','五级重度污染','六级严重污染'])
print('对AQI的分组结果：\n{0}'.format(data[['日期','AQI','等级','季度']]))

对AQI的分组结果：
             日期    AQI      等级   季度
0    2014-01-01   81.0     二级良  一季度
1    2014-01-02  145.0  三级轻度污染  一季度
2    2014-01-03   74.0     二级良  一季度
3    2014-01-04  149.0  三级轻度污染  一季度
4    2014-01-05  119.0  三级轻度污染  一季度
...         ...    ...     ...  ...
2150 2019-11-22  183.0  四级中度污染  四季度
2151 2019-11-23  175.0  四级中度污染  四季度
2152 2019-11-24   30.0     一级优  四季度
2153 2019-11-25   40.0     一级优  四季度
2154 2019-11-26   73.0     二级良  四季度

[2155 rows x 4 columns]


In [5]:
from collections import Iterable
isinstance(month,Iterable)   #判断month是否为可迭代的对象


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  """Entry point for launching an IPython kernel.


True

代码说明：
（1）第6行：利用数据框函数replace()将数据框中的0（表示无监测结果）替换为缺失值NaN。
（2）第7，8行：利用.apply()方法以及匿名函数，基于“日期”变量得到每个样本观测的年份和月份。
（3）第9行：建立一个关于月份和季度的字典quarter_month。
（4）第10行：利用Python函数map()，依据字典quarter_month，将序列month中的1，2，3等月份映射（对应）到相应的季度上。
（5）第14行：生成一个后续用于对AQI分组的列表bins。它描述了AQI和空气质量等级的数值对应关系。
（6）第15行：利用Pandas的cut()方法对AQI进行分组。

In [6]:
print('各季度AQI和PM2.5的均值:\n{0}'.format(data.loc[:,['AQI','PM2.5']].groupby(data['季度']).mean()))
print('各季度AQI和PM2.5的描述统计量:\n',data.groupby(data['季度'])['AQI','PM2.5'].apply(lambda x:x.describe()))

def top(df,n=10,column='AQI'):
    return df.sort_values(by=column,ascending=False)[:n]
print('空气质量最差的5天:\n',top(data,n=5)[['日期','AQI','PM2.5','等级']])
print('各季度空气质量最差的3天:\n',data.groupby(data['季度']).apply(lambda x:top(x,n=3)[['日期','AQI','PM2.5','等级']]))
print('各季度空气质量情况:\n',pd.crosstab(data['等级'],data['季度'],margins=True,margins_name='总计',normalize=False))

各季度AQI和PM2.5的均值:
            AQI      PM2.5
季度                        
一季度  109.327778  77.225926
三季度   98.911071  49.528131
二季度  109.369004  55.149723
四季度  109.612403  77.195736
各季度AQI和PM2.5的描述统计量:
                   AQI       PM2.5
季度                               
一季度 count  540.000000  540.000000
    mean   109.327778   77.225926
    std     80.405408   73.133857
    min     26.000000    4.000000
    25%     48.000000   24.000000
    50%     80.000000   53.000000
    75%    145.000000  109.250000
    max    470.000000  454.000000
三季度 count  551.000000  551.000000
    mean    98.911071   49.528131
    std     45.484516   35.394897
    min     28.000000    3.000000
    25%     60.000000   23.000000
    50%     95.000000   41.000000
    75%    130.500000   67.000000
    max    252.000000  202.000000
二季度 count  542.000000  541.000000
    mean   109.369004   55.149723
    std     49.608042   35.918345
    min     35.000000    5.000000
    25%     71.000000   27.000000
    50%     99.000

代码说明：
（1）第1行：利用数据框的groupby()方法，计算各季度AQI和PM2.5的平均值。
（2）第2行：计算几个季度AQI和PM2.5的基本描述统计量（均值，标准差，最小值，四分位数，最大值）。
（3）第4，5行：定义了一个名为top的用户自定义函数：对给定数据框，按指定列（默认AQI列）值的降序排序，返回排在前n（默认10）条数据。
（4）第6行：调用用户自定义函数top，对data数据框中，按AQI值的降序排序并返回前5条数据，即AQI最高的5天的数据。
（5）第7行：首先对数据按季度分组，依次对分组数据调用用户自定义函数top，得到各季度AQI最高的3天数据。
（6）第8行：利用Pandas函数crosstab()对数据按季度和空气质量等级交叉分组，并给出各个组的样本量。

In [7]:
pd.get_dummies(data['等级'])
data.join(pd.get_dummies(data['等级']))

日期    AQI  质量等级  PM2.5   PM10   SO2   CO   NO2    O3     年   季度  \
0    2014-01-01   81.0     良   45.0  111.0  28.0  1.5  62.0  52.0  2014  一季度   
1    2014-01-02  145.0  轻度污染  111.0  168.0  69.0  3.4  93.0  14.0  2014  一季度   
2    2014-01-03   74.0     良   47.0   98.0  29.0  1.3  52.0  56.0  2014  一季度   
3    2014-01-04  149.0  轻度污染  114.0  147.0  40.0  2.8  75.0  14.0  2014  一季度   
4    2014-01-05  119.0  轻度污染   91.0  117.0  36.0  2.3  67.0  44.0  2014  一季度   
...         ...    ...   ...    ...    ...   ...  ...   ...   ...   ...  ...   
2150 2019-11-22  183.0  中度污染  138.0  181.0   9.0  2.4  94.0   5.0  2019  四季度   
2151 2019-11-23  175.0  中度污染  132.0  137.0   6.0  1.6  69.0  34.0  2019  四季度   
2152 2019-11-24   30.0     优    7.0   30.0   3.0  0.2  11.0  58.0  2019  四季度   
2153 2019-11-25   40.0     优   13.0   30.0   3.0  0.4  32.0  29.0  2019  四季度   
2154 2019-11-26   73.0     良   38.0   72.0   6.0  0.8  58.0  14.0  2019  四季度   

          等级  一级优  二级良  三级轻度污染  四级中度污染  五级重度污染  六级严重污染  
0        二级良    0    1       0       0       0       0  
1     三级轻度污染    0    0       1       0       0       0  
2        二级良    0    1       0       0       0       0  
3     三级轻度污染    0    0       1       0       0       0  
4     三级轻度污染    0    0       1       0       0       0  
...      ...  ...  ...     ...     ...     ...     ...  
2150  四级中度污染    0    0       0       1       0       0  
2151  四级中度污染    0    0       0       1       0       0  
2152     一级优    1    0       0       0       0       0  
2153     一级优    1    0       0       0       0       0  
2154     二级良    0    1       0       0       0       0  

[2155 rows x 18 columns]

代码说明：
（1）第1行：利用Pandas的get_dummies得到分类型变量“等级”的哑变量。
（2）第2行：利用数据框的join()方法，将原始数据和哑变量数据，按行索引进行横向合并。

In [8]:
np.random.seed(123)
sampler=np.random.randint(0,len(data),10)
print(sampler)
sampler=np.random.permutation(len(data))[:10]
print(sampler)

data.take(sampler)
data.loc[data['质量等级']=='优',:]

[1346 1122 1766 2154 1147 1593 1761   96   47   73]
[1883  326   43 1627 1750 1440  993 1469 1892  865]


日期   AQI 质量等级  PM2.5  PM10   SO2   CO   NO2    O3     年   季度   等级
7    2014-01-08  27.0    优   15.0  25.0  13.0  0.5  21.0  53.0  2014  一季度  一级优
8    2014-01-09  46.0    优   27.0  46.0  19.0  0.8  35.0  53.0  2014  一季度  一级优
11   2014-01-12  47.0    优   27.0  47.0  27.0  0.7  39.0  59.0  2014  一季度  一级优
19   2014-01-20  35.0    优    8.0  35.0   6.0  0.3  15.0  65.0  2014  一季度  一级优
20   2014-01-21  26.0    优   18.0  25.0  27.0  0.7  34.0  50.0  2014  一季度  一级优
...         ...   ...  ...    ...   ...   ...  ...   ...   ...   ...  ...  ...
2122 2019-10-25  30.0    优    8.0  20.0   2.0  0.4  24.0  55.0  2019  四季度  一级优
2131 2019-11-03  48.0    优   33.0  48.0   3.0  0.6  34.0  33.0  2019  四季度  一级优
2135 2019-11-07  47.0    优   24.0  47.0   3.0  0.5  37.0  44.0  2019  四季度  一级优
2152 2019-11-24  30.0    优    7.0  30.0   3.0  0.2  11.0  58.0  2019  四季度  一级优
2153 2019-11-25  40.0    优   13.0  30.0   3.0  0.4  32.0  29.0  2019  四季度  一级优

[387 rows x 12 columns]

代码说明：
（1）第2行：利用Pandas函数random.randint()在指定范围内随机抽取指定个数（这里是10）的随机数。
（2）第 4行：利用Pandas函数random.permutation是对数据随机打乱重排。之后再抽取前10个样本观测。
（3）第7行：利用数据框的take()方法，基于指定随机数获得数据集的一个子集。
（4）第8行：利用数据框访问的方式，抽取满足指定条件（质量等级等于优）行的数据。
